///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginVoData {

  String uid;
  String uname;
  String avatar;
  String phone;
  String email;
  String gender;
  String ulevel;
  String wechat;
  String score;
  String status;
  String regip;
  String source;
  String referer;
  String reason;
  String qq;
  String address;
  bool newUser;
  bool setPwd;
  String accessToken;
  int tokenExpireTime;
  bool isSetPwd;
  String realName;
  String userExtra;
  String ulevelName;
  String userLevel;
  String bindStatus;
  String lastLoginIp;
  String lastLoginTime;
  String putongScore;
  String hunzuanScore;
  String faceId;
  String settingStatus;
  String perfectBind;
  String cityId;
  String createTime;
  String creativeScore;
  String loveId;
  String hbhId;
  String autoLoginKey;
  String markStatus;
  String honorValue;
  String qrcodeImg;
  String liveCity;
  String clientIp;

  LoginVoData({
    this.uid,
    this.uname,
    this.avatar,
    this.phone,
    this.email,
    this.gender,
    this.ulevel,
    this.wechat,
    this.score,
    this.status,
    this.regip,
    this.source,
    this.referer,
    this.reason,
    this.qq,
    this.address,
    this.newUser,
    this.setPwd,
    this.accessToken,
    this.tokenExpireTime,
    this.isSetPwd,
    this.realName,
    this.userExtra,
    this.ulevelName,
    this.userLevel,
    this.bindStatus,
    this.lastLoginIp,
    this.lastLoginTime,
    this.putongScore,
    this.hunzuanScore,
    this.faceId,
    this.settingStatus,
    this.perfectBind,
    this.cityId,
    this.createTime,
    this.creativeScore,
    this.loveId,
    this.hbhId,
    this.autoLoginKey,
    this.markStatus,
    this.honorValue,
    this.qrcodeImg,
    this.liveCity,
    this.clientIp,
  });
  LoginVoData.fromJson(Map<String, dynamic> json) {
    uid = json["uid"]?.toString();
    uname = json["uname"]?.toString();
    avatar = json["avatar"]?.toString();
    phone = json["phone"]?.toString();
    email = json["email"]?.toString();
    gender = json["gender"]?.toString();
    ulevel = json["ulevel"]?.toString();
    wechat = json["wechat"]?.toString();
    score = json["score"]?.toString();
    status = json["status"]?.toString();
    regip = json["regip"]?.toString();
    source = json["source"]?.toString();
    referer = json["referer"]?.toString();
    reason = json["reason"]?.toString();
    qq = json["qq"]?.toString();
    address = json["address"]?.toString();
    newUser = json["newUser"];
    setPwd = json["setPwd"];
    accessToken = json["access_token"]?.toString();
    tokenExpireTime = json["token_expire_time"]?.toInt();
    isSetPwd = json["is_set_pwd"];
    realName = json["real_name"]?.toString();
    userExtra = json["user_extra"]?.toString();
    ulevelName = json["ulevel_name"]?.toString();
    userLevel = json["user_level"]?.toString();
    bindStatus = json["bind_status"]?.toString();
    lastLoginIp = json["last_login_ip"]?.toString();
    lastLoginTime = json["last_login_time"]?.toString();
    putongScore = json["putong_score"]?.toString();
    hunzuanScore = json["hunzuan_score"]?.toString();
    faceId = json["face_id"]?.toString();
    settingStatus = json["setting_status"]?.toString();
    perfectBind = json["perfect_bind"]?.toString();
    cityId = json["city_id"]?.toString();
    createTime = json["create_time"]?.toString();
    creativeScore = json["creative_score"]?.toString();
    loveId = json["love_id"]?.toString();
    hbhId = json["hbh_id"]?.toString();
    autoLoginKey = json["auto_login_key"]?.toString();
    markStatus = json["mark_status"]?.toString();
    honorValue = json["honor_value"]?.toString();
    qrcodeImg = json["qrcode_img"]?.toString();
    liveCity = json["live_city"]?.toString();
    clientIp = json["client_ip"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["uid"] = uid;
    data["uname"] = uname;
    data["avatar"] = avatar;
    data["phone"] = phone;
    data["email"] = email;
    data["gender"] = gender;
    data["ulevel"] = ulevel;
    data["wechat"] = wechat;
    data["score"] = score;
    data["status"] = status;
    data["regip"] = regip;
    data["source"] = source;
    data["referer"] = referer;
    data["reason"] = reason;
    data["qq"] = qq;
    data["address"] = address;
    data["newUser"] = newUser;
    data["setPwd"] = setPwd;
    data["access_token"] = accessToken;
    data["token_expire_time"] = tokenExpireTime;
    data["is_set_pwd"] = isSetPwd;
    data["real_name"] = realName;
    data["user_extra"] = userExtra;
    data["ulevel_name"] = ulevelName;
    data["user_level"] = userLevel;
    data["bind_status"] = bindStatus;
    data["last_login_ip"] = lastLoginIp;
    data["last_login_time"] = lastLoginTime;
    data["putong_score"] = putongScore;
    data["hunzuan_score"] = hunzuanScore;
    data["face_id"] = faceId;
    data["setting_status"] = settingStatus;
    data["perfect_bind"] = perfectBind;
    data["city_id"] = cityId;
    data["create_time"] = createTime;
    data["creative_score"] = creativeScore;
    data["love_id"] = loveId;
    data["hbh_id"] = hbhId;
    data["auto_login_key"] = autoLoginKey;
    data["mark_status"] = markStatus;
    data["honor_value"] = honorValue;
    data["qrcode_img"] = qrcodeImg;
    data["live_city"] = liveCity;
    data["client_ip"] = clientIp;
    return data;
  }
}

class LoginVo {

  int code;
  String message;
  LoginVoData data;
  int serviceTime;
  bool success;

  LoginVo({
    this.code,
    this.message,
    this.data,
    this.serviceTime,
    this.success,
  });
  LoginVo.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    message = json["message"]?.toString();
    data = json["data"] != null ? LoginVoData.fromJson(json["data"]) : null;
    serviceTime = json["serviceTime"]?.toInt();
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    data["serviceTime"] = serviceTime;
    data["success"] = success;
    return data;
  }
}
